services:
  - type: web
    name: webfpga-backend
    env: node
    buildCommand: npm install --prefix src/Backend
    startCommand: npm run server --prefix src/Backend
  - type: static
    name: webfpga-frontend
    buildCommand: npm install --prefix src/Frontend && npm run build --prefix src/Frontend
    publishDir: src/Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
